# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [5]:
import numpy as np
np10 = np.arange(1, 11)
print(np10)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [7]:
np_0_3by3 = np.zeros((3,3))
np_0_3by3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [8]:
np_lin1 = np.linspace(0,5,10)
np_lin1

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [9]:
np_identity_5 = np.eye(5)
np_identity_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [10]:
np_random_4by4 = np.random.random((4,4))
np_random_4by4

array([[0.88400667, 0.33629682, 0.66717648, 0.72179006],
       [0.70824252, 0.23684514, 0.16153287, 0.97276456],
       [0.10790582, 0.66652498, 0.57180976, 0.82041619],
       [0.33416969, 0.12292564, 0.46995782, 0.00312109]])

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [11]:
np_random_4by4.shape

(4, 4)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [12]:
np16 = np.arange(16).reshape(4,4)
np16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [13]:
np16.dtype

dtype('int32')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [17]:
np_1_100 = np.arange(1,101)
np_1_100 = np_1_100[1::2]
#np_1_100 = [k for k in np_1_100 if k%2==0]
np_1_100

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [22]:
np_6by6 = np.random.randint(10,50,size=(6,6))
np_6by6

array([[35, 19, 21, 15, 46, 11],
       [33, 42, 33, 46, 15, 34],
       [48, 41, 33, 13, 33, 11],
       [27, 21, 26, 37, 19, 16],
       [44, 32, 22, 36, 14, 20],
       [34, 44, 36, 19, 37, 44]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [36]:
np_data_slice = np.random.randint(10, size=(3, 4))
np_data_slice_sub = np_data_slice[:, 2:]
np_data_slice_sub

array([[1, 9],
       [2, 1],
       [0, 5]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [23]:
np.sum(np_6by6)

1057

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [28]:
np_data1 = np.arange(1, 101)
np_data1_mean = np.mean(np_data1)
np_data1_std = np.std(np_data1)
np_data1_median = np.median(np_data1)
print(np_data1_mean)
print('\n=========================================================\n')
print(np_data1_median)
print('\n=========================================================\n')
np_data1_std

50.5


50.5




28.86607004772212

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [29]:
np_data2 = np.random.randint(50, size=50)
print(np.max(np_data2))
print('\n==================================================\n')
np.min(np_data2)

49




0

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [32]:
np_rand_20 = np.random.randint(1000, size=20)
print(np.where(np_rand_20 == np.max(np_rand_20 ))[0][0])

14


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [34]:
np_data_rev = np.arange(25)[::-1]
np_data_rev

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [37]:
np_3by3_1 = np.random.randint(100, size=(3,3))
np_3by3_2 = np.random.randint(100, size=(3,3))
print(np.multiply(np_3by3_1, np_3by3_2))

[[7227 1728 3116]
 [1364 7392 3168]
 [6231 4650 8170]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [40]:
np_diag = np.arange(9).reshape(3,3)
np_diag = np.diag(np.diag(np_diag))
np_diag

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [44]:
np_2D_1 = np.random.randint(10, size=(4, 4))
np_2D_2 = np.random.randint(10, size=(4, 4))
print(np.multiply(np_2D_1,np_2D_2))

[[ 9  0 12 30]
 [28 72 56  0]
 [42  9 14  0]
 [ 4 25 20  0]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [49]:
np_2D_3 = np.random.randint(10, size=(4, 4))
print(np_2D_3)
print('\n=============================================================\n')
np_2D_3 = np_2D_3.reshape(np.prod(np_2D_3.shape))
np_2D_3

[[0 5 9 3]
 [9 6 9 7]
 [8 0 9 6]
 [0 1 0 1]]




array([0, 5, 9, 3, 9, 6, 9, 7, 8, 0, 9, 6, 0, 1, 0, 1])

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [52]:
np_data_ver1 = np.random.randint(10, size=(2,2))
np_data_ver2 = np.random.randint(10, size=(2,2))
np_data_ver3 = np.vstack((np_data_ver1, np_data_ver2))
np_data_ver3

array([[4, 4],
       [1, 1],
       [2, 1],
       [1, 2]])

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [53]:
np_data_h1 = np.random.randint(10, size=(2,2))
np_data_h2 = np.random.randint(10, size=(2,2))
np_data_h3 = np.hstack((np_data_ver1, np_data_ver2))
np_data_h3

array([[4, 4, 2, 1],
       [1, 1, 1, 2]])

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [54]:
np_split = np.arange(100)
np.split(np_split,10)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [56]:
np_rand = np.random.random(100)
np.around(np_rand, decimals=2)

array([0.91, 0.58, 0.09, 0.12, 0.77, 0.73, 0.09, 0.36, 0.77, 0.13, 0.54,
       0.75, 0.27, 0.57, 0.48, 0.56, 0.44, 0.69, 0.72, 0.76, 0.04, 0.68,
       0.48, 0.1 , 0.61, 0.84, 0.73, 0.32, 0.07, 0.04, 0.56, 0.16, 0.27,
       0.24, 0.02, 0.15, 0.03, 0.98, 0.36, 0.83, 0.41, 0.25, 0.24, 0.77,
       0.67, 0.71, 0.85, 0.52, 0.44, 0.55, 0.65, 0.79, 0.89, 0.31, 0.14,
       0.75, 0.53, 0.78, 0.43, 0.84, 0.54, 0.25, 0.06, 0.09, 0.17, 0.44,
       0.81, 0.91, 0.58, 0.29, 0.65, 0.64, 0.5 , 0.97, 0.81, 0.93, 0.61,
       0.98, 0.71, 0.01, 0.29, 0.84, 0.44, 0.17, 0.11, 0.8 , 0.65, 0.5 ,
       0.29, 0.64, 0.37, 0.54, 0.76, 0.84, 0.1 , 0.51, 0.65, 0.15, 0.  ,
       0.97])

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [57]:
np_unique = np.random.randint(10, size=100)
np.unique(np_unique)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---

In [24]:
np.random.seed(10)

In [25]:
A = np.random.rand(2,2)
A

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388]])